version: "3.8"

services:
  nodeapp:
    container_name: my-nodejs-app-dev
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate && npm run dev"
  db:
    image: postgres:latest
    container_name: my-postgres-dev
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nawy-db-11
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    container_name: my-nextjs-app-dev
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "npm run dev"
volumes:
  postgres-data: {}
